/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.requestview;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.controllers.ProjectsController;
import sv.edu.udb.controllers.RequestController;
import sv.edu.udb.controllers.RequestTypeController;
import sv.edu.udb.models.Request;
import sv.edu.udb.models.Session;
/**
 *
 * @author Imer Palma
 */
public class RequestList extends javax.swing.JInternalFrame {

    /**
     * Creates new form RequestList
     */
    ResultSet tabla;

    Request reOb = new Request();
    RequestController reControl = new RequestController();
    List<Request> listRe = new ArrayList<>();
    ProjectsController proControl = new ProjectsController();
    RequestTypeController rtControl= new RequestTypeController();
    DefaultTableModel modelo1;
    public RequestList() {
        initComponents();
        loadData();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Lista de solicitudes ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadData(){
       
        Object[][] data = null;
        String[] columns = {
            "Id Solicitud", "Tipo de solicitud", "Projecto", "Fecha de solicitud", "Descripcion", "Estatus"
        };
        modelo1 = new DefaultTableModel(data, columns);
        this.jTable1.setModel(modelo1);
       
       
                listRe = reControl.getRequests();
               
       
            for (Request request : listRe) {
                   Object[] newRow = { request.getId(),request.getIdTypeRequest(), request.getProjectId(), request.getRequestDate()
                           ,request.getRequestDescription(),request.getRequestStatus()
                   };
                   modelo1.addRow(newRow);  
            } 
           
               
               
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
