/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.tickets;

import java.awt.Dimension;
import java.util.Date;
import java.util.List;
import sv.edu.udb.controllers.ProjectsController;
import sv.edu.udb.controllers.RequestController;
import sv.edu.udb.controllers.RequestTypeController;
import sv.edu.udb.models.Project;
import sv.edu.udb.models.Request;
import sv.edu.udb.models.RequestType;
import sv.edu.udb.util.RequestStatus;
import sv.edu.udb.util.RequestTypes;
import static sv.edu.udb.vistas.Contenedor.desktopPane;

/**
 *
 * @author Rick
 */
public class CreateRequest extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateRequest
     */
    public CreateRequest() {
        initComponents();
        cargarTiposSolicitud();
        cargarProyectosExistentesPorDepartamento();

        //center internalframe based on main container
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }
    
    private void cargarTiposSolicitud() {
        RequestTypeController controller = new RequestTypeController();
        List<RequestType> types = controller.findRequestTypes();
        
        cbTipoSolicitud.removeAllItems();
        for (RequestType type : types) {
            cbTipoSolicitud.addItem(type.getRequestTypeName());
        }
        cbTipoSolicitud.setSelectedIndex(1);
    }
    
    private void cargarProyectosExistentesPorDepartamento() {
        ProjectsController controller = new ProjectsController();
        List<Project> projects = controller.projectsByDepto();
        
        cbProyectosExistentes.removeAllItems();
        for (Project project : projects) {
            cbProyectosExistentes.addItem(project.getProjectName() + " ("
                    + project.getProjectsId() + ")");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoSolicitud = new javax.swing.JComboBox<>();
        lblTipoSolicitud = new javax.swing.JLabel();
        cbProyectosExistentes = new javax.swing.JComboBox<>();
        lblProyectosExistentes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionRequerimiento = new javax.swing.JTextArea();
        lblDescripcionReq = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Requerimiento");

        cbTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoSolicitud.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoSolicitudItemStateChanged(evt);
            }
        });

        lblTipoSolicitud.setText("Tipo de solicitud: ");

        cbProyectosExistentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblProyectosExistentes.setText("Proyecto existente: ");

        txtDescripcionRequerimiento.setColumns(20);
        txtDescripcionRequerimiento.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionRequerimiento);

        lblDescripcionReq.setText("Descripcion de requerimiento:");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProyectosExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbProyectosExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescripcionReq)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoSolicitud)
                    .addComponent(cbTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProyectosExistentes)
                    .addComponent(cbProyectosExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblDescripcionReq)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnLimpiar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDescripcionRequerimiento.setText("");
        cbProyectosExistentes.setSelectedIndex(0);
        cbTipoSolicitud.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // enviar notificacion a jefe de desarrollo del area
        // setear estado a: en espera de respuesta
        // mostrar dialogo con ID
        int requestTypeID = Integer.parseInt(String.valueOf(
                cbTipoSolicitud.getSelectedItem()).split("(")[1].replace(")", "").trim());
        
        Request r = new Request();
        r.setIdTypeRequest(requestTypeID);
        r.setRequestDate(new Date());
        r.setRequestDescription(txtDescripcionRequerimiento.getText());
        r.setRequestStatus(RequestStatus.EN_ESPERA.name());
        
        RequestController controller = new RequestController();
        controller.insertRequest(r);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbTipoSolicitudItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoSolicitudItemStateChanged
        String selectedItemText = String.valueOf(cbTipoSolicitud.getSelectedItem());
        if (selectedItemText.contains(RequestTypes.NUEVA_FUNCIONALIDAD.name())
                || selectedItemText.contains(RequestTypes.CORRECION.name())) {
            cbProyectosExistentes.setSelectedIndex(0);
            cbProyectosExistentes.setEnabled(true);
        } else {
            cbProyectosExistentes.setSelectedIndex(-1);
            cbProyectosExistentes.setEnabled(false);
        }
    }//GEN-LAST:event_cbTipoSolicitudItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbProyectosExistentes;
    private javax.swing.JComboBox<String> cbTipoSolicitud;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionReq;
    private javax.swing.JLabel lblProyectosExistentes;
    private javax.swing.JLabel lblTipoSolicitud;
    private javax.swing.JTextArea txtDescripcionRequerimiento;
    // End of variables declaration//GEN-END:variables
}
