/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.tickets;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.controllers.TicketsController;
import sv.edu.udb.models.Session;
import sv.edu.udb.models.Ticket;
import sv.edu.udb.util.Roles;
import sv.edu.udb.vistas.Contenedor;
import sv.edu.udb.vistas.employessviews.EditUser;

/**
 *
 * @author Imer Palma
 */
public class TicketsList extends javax.swing.JInternalFrame {

    ResultSet tabla;
    Ticket tickOb = new Ticket();
    TicketsController ticketController = new TicketsController();
    List<Ticket> tList = new ArrayList<>();
    TicketsController proTicket = new TicketsController();

    /**
     * Creates new form ViewTickets
     */
    public TicketsList() {
        initComponents();
        loadData();
        showTickets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "InternalCode", "Request", "Project", "Status"
            }
        ));
        tblTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTicketsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTickets);

        jLabel1.setText("Lista de tickets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTicketsMouseClicked
        // TODO add your handling code here:
        int rowNumber = tblTickets.getSelectedRow();
//        JOptionPane.showMessageDialog(rootPane, rowNumber);
        String cod = tblTickets.getValueAt(rowNumber, 0).toString();
//        JOptionPane.showMessageDialog(rootPane, Integer.parseInt(cod));
        ViewTicket vt = new ViewTicket(Integer.parseInt(cod));
            Contenedor.desktopPane.removeAll();
            Contenedor.desktopPane.updateUI();
            Contenedor.desktopPane.add(vt);
            this.dispose();
            vt.show();
    }//GEN-LAST:event_tblTicketsMouseClicked

    private void showTickets() {
        String matriz[][] = new String[tList.size()][5];

        for (int i = 0; i < tList.size(); i++) {
            matriz[i][0] = Integer.toString(tList.get(i).getIdTicket());
            matriz[i][1] = tList.get(i).getInternalCode();
            matriz[i][2] = Integer.toString(tList.get(i).getRequestId());
            matriz[i][3] = Integer.toString(tList.get(i).getProjectID());
            matriz[i][4] = tList.get(i).getTicketStatus();
        }
        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "InternalCode", "Request", "Project", "Status"
                }
        ));

    }

    public void loadData() {
        if (Session.employeeType == Roles.ADMINISTRADOR.getRolId()) {
            tList = proTicket.getAllTickets();
        }
        else{
        tList = proTicket.getAllTickets(Session.deparmentId);    
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTickets;
    // End of variables declaration//GEN-END:variables

}
