/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.tickets;

/**
 *
 * @author kiss_
 */
public class ViewTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewTicket
     */
    public ViewTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfoTicket = new javax.swing.JPanel();
        lblAvance = new javax.swing.JLabel();
        txtAvance = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblTituloSup = new javax.swing.JLabel();
        lblSupervisorProgra = new javax.swing.JLabel();
        lblTituloSuper = new javax.swing.JLabel();
        lblSuperFunc = new javax.swing.JLabel();
        chkbxQA = new javax.swing.JCheckBox();
        cmbQA = new javax.swing.JComboBox<>();
        lblFechaStart = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();
        txtFechaStart = new javax.swing.JTextField();
        txtFechaFinal = new javax.swing.JTextField();
        lvlTicketName = new javax.swing.JLabel();
        lblTDes = new javax.swing.JLabel();
        lblDescripcionAd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        lblActividad = new javax.swing.JLabel();
        btnComentario = new javax.swing.JButton();
        pnlComentarios = new javax.swing.JPanel();

        pnlInfoTicket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAvance.setText("Avance");

        txtAvance.setText("jTextField1");

        lblEstado.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTituloSup.setText("Supervisor de TI");

        lblSupervisorProgra.setText("jLabel1");

        lblTituloSuper.setText("Supervisor administrativo");

        lblSuperFunc.setText("jLabel1");

        chkbxQA.setText("Q/A Asignado");

        cmbQA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFechaStart.setText("jLabel1");

        lblFechaFinal.setText("jLabel2");

        txtFechaStart.setText("jTextField1");

        txtFechaFinal.setText("jTextField2");

        javax.swing.GroupLayout pnlInfoTicketLayout = new javax.swing.GroupLayout(pnlInfoTicket);
        pnlInfoTicket.setLayout(pnlInfoTicketLayout);
        pnlInfoTicketLayout.setHorizontalGroup(
            pnlInfoTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoTicketLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlInfoTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFinal)
                    .addComponent(cmbQA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbxQA)
                    .addComponent(lblSuperFunc)
                    .addComponent(lblSupervisorProgra)
                    .addComponent(lblTituloSup)
                    .addGroup(pnlInfoTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblEstado)
                        .addComponent(txtAvance)
                        .addComponent(lblAvance)
                        .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInfoTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlInfoTicketLayout.createSequentialGroup()
                            .addComponent(lblFechaStart)
                            .addGap(87, 87, 87))
                        .addComponent(lblTituloSuper)
                        .addComponent(txtFechaStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlInfoTicketLayout.setVerticalGroup(
            pnlInfoTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoTicketLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAvance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloSup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupervisorProgra)
                .addGap(18, 18, 18)
                .addComponent(lblTituloSuper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSuperFunc)
                .addGap(18, 18, 18)
                .addComponent(chkbxQA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbQA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lvlTicketName.setText("Nombre del Ticket");

        lblTDes.setText("Descripcion");

        lblDescripcionAd.setText("jLabel2");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        txtComentario.setText("Comentario de jefe IT");
        jScrollPane1.setViewportView(txtComentario);

        lblActividad.setText("Actividad");

        btnComentario.setText("Insertar comentarios");
        btnComentario.setActionCommand("");

        pnlComentarios.setAutoscrolls(true);

        javax.swing.GroupLayout pnlComentariosLayout = new javax.swing.GroupLayout(pnlComentarios);
        pnlComentarios.setLayout(pnlComentariosLayout);
        pnlComentariosLayout.setHorizontalGroup(
            pnlComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlComentariosLayout.setVerticalGroup(
            pnlComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lvlTicketName)
                        .addGap(18, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComentario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDescripcionAd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblActividad)
                                            .addComponent(lblTDes))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)))
                .addComponent(pnlInfoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInfoTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lvlTicketName)
                .addGap(25, 25, 25)
                .addComponent(lblTDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcionAd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComentario)
                .addGap(17, 17, 17)
                .addComponent(lblActividad)
                .addGap(18, 18, 18)
                .addComponent(pnlComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentario;
    private javax.swing.JCheckBox chckbQA;
    private javax.swing.JCheckBox chkbxQA;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbProgramador;
    private javax.swing.JComboBox<String> cmbQA;
    private javax.swing.JComboBox<String> cmbTester;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblAvance;
    private javax.swing.JLabel lblDescripcionAd;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecgaFin;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaStart;
    private javax.swing.JLabel lblSuperFunc;
    private javax.swing.JLabel lblSupervisorFunc;
    private javax.swing.JLabel lblSupervisorProgra;
    private javax.swing.JLabel lblSupervisorTI;
    private javax.swing.JLabel lblTDes;
    private javax.swing.JLabel lblTitleProgramador1;
    private javax.swing.JLabel lblTitleStatus;
    private javax.swing.JLabel lblTitleStatus1;
    private javax.swing.JLabel lblTitleSupervisor;
    private javax.swing.JLabel lblTitleSupervisor1;
    private javax.swing.JLabel lblTituloSup;
    private javax.swing.JLabel lblTituloSuper;
    private javax.swing.JLabel lvlTicketName;
    private javax.swing.JPanel pnlComentarios;
    private javax.swing.JPanel pnlInfoTicket;
    private javax.swing.JTextField txtAvance;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaStart;
    private javax.swing.JFormattedTextField txtPorcentaje;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
