/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.employessviews;

import sv.edu.udb.controllers.DeparmentController;
import sv.edu.udb.controllers.RolController;
import sv.edu.udb.controllers.EmployeeController;
import javax.swing.*;
import sv.edu.udb.util.*;
import sv.edu.udb.models.Session;
import java.util.List;
import java.util.ArrayList;
import sv.edu.udb.models.Deparment;
import sv.edu.udb.models.Employee;
import sv.edu.udb.models.Rol;
import sv.edu.udb.util.Roles;

/**
 *
 * @author kiss_
 */
public class CreateUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateUser
     */
   private DeparmentController dep = new DeparmentController();
   private RolController rol = new RolController();
   private List<Deparment> listaDep = new ArrayList<>();
   private Deparment liDep = new Deparment();
   private List<Rol> listaRol = new ArrayList<>();
   private Rol liRol = new Rol();
   Validations valid=new Validations();
    public CreateUser() {
        initComponents();

        if (Session.employeeType == Roles.ADMINISTRADOR.getRolId()) {
            listaDep = dep.showDeparment();
            listaRol = rol.showRol();
        } else {
            liDep = dep.showDeparment(Session.deparmentId);
            liRol = rol.showRol(Session.employeeType);
        }
        cmbbxDepoto.removeAllItems();
        cmbbxTipoEmpleado.removeAllItems();

        if (listaDep.isEmpty()) {
            cmbbxDepoto.addItem(liDep.getDepartmentName());
            cmbbxTipoEmpleado.addItem(liRol.getRolName());
        } else {
            listaDep.forEach((deparment) -> {
                cmbbxDepoto.addItem(deparment.getDepartmentName());
            });
            listaRol.forEach((rol) -> {
                cmbbxTipoEmpleado.addItem(rol.getRolName());
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        cmbbxTipoEmpleado = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblUsers = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblDepto = new javax.swing.JLabel();
        cmbbxDepoto = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        lblTipo.setForeground(new java.awt.Color(0, 41, 250));
        lblTipo.setText("Tipo de empleado:");

        cmbbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombre.setForeground(new java.awt.Color(0, 41, 250));
        lblNombre.setText("Nombre:");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        lblApellido.setForeground(new java.awt.Color(0, 41, 250));
        lblApellido.setText("Apellido:");

        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastnameKeyTyped(evt);
            }
        });

        lblUsers.setForeground(new java.awt.Color(0, 41, 250));
        lblUsers.setText("Usuario:");

        lblContra.setForeground(new java.awt.Color(0, 41, 250));
        lblContra.setText("Contraseña:");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(35, 10, 89));
        lblTitulo.setText("Registro de nuevo empleado");

        btnIngresar.setBackground(new java.awt.Color(35, 10, 89));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblDepto.setForeground(new java.awt.Color(0, 41, 250));
        lblDepto.setText("Departamento:");

        cmbbxDepoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsers)
                        .addComponent(lblApellido)
                        .addComponent(lblNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblContra))
                    .addComponent(lblDepto)
                    .addComponent(lblTipo))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbbxTipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbbxDepoto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastname)
                    .addComponent(txtName)
                    .addComponent(txtUsuario)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnIngresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbbxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbxDepoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepto))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContra))
                .addGap(31, 31, 31)
                .addComponent(btnIngresar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        Employee user = new Employee();
        DeparmentController depto = new DeparmentController();
        RolController rolUser = new RolController();
        EmployeeController ec = new EmployeeController();
        Deparment d = new Deparment();
       
       
        
        if ( valid.checkPassword(txtContra.getPassword()) &&  !valid.emptyField(txtName.getText()) && !valid.emptyField(txtLastname.getText())) {
            String pass = new String(txtContra.getPassword());
            user.setEmployeeName(txtName.getText());
            user.setEmployeeLastname(txtLastname.getText());
            user.setUsername(txtUsuario.getText());
            user.setPassword(pass);
            d = depto.showDepartment(cmbbxDepoto.getSelectedItem().toString());
            user.setDepartmentId(d.getDepartmentId());
            user.setRolId(rolUser.showID(cmbbxTipoEmpleado.getSelectedItem().toString()));
        
            if (ec.insertEmployee(user)) {
                JOptionPane.showMessageDialog(null, "El usuario se ha insertado correctamente", "Operacion exitosa", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(null, "El usuario no se ha insertado correctamente", "Operacion fallida", JOptionPane.ERROR_MESSAGE);
                
            }
        }
        else {
                JOptionPane.showMessageDialog(null, "Datos ingresados incorrectamente", "Operacion fallida", JOptionPane.ERROR_MESSAGE);
                clearForm();
            }
        

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
       
        valid.numberTyped(evt);
        
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyTyped
        // TODO add your handling code here:
       
        valid.numberTyped(evt);

    }//GEN-LAST:event_txtLastnameKeyTyped

    private void clearForm() {
        txtName.setText("");
        txtLastname.setText("");
        txtUsuario.setText("");
        txtContra.setText("");

    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbbxDepoto;
    private javax.swing.JComboBox<String> cmbbxTipoEmpleado;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblDepto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
