/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.employessviews;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sv.edu.udb.controllers.DeparmentController;
import sv.edu.udb.controllers.EmployeeController;
import sv.edu.udb.controllers.RolController;
import sv.edu.udb.controllers.EmployeeController;
import sv.edu.udb.models.Deparment;
import sv.edu.udb.models.Employee;
import sv.edu.udb.models.Rol;
import sv.edu.udb.models.Session;
import sv.edu.udb.util.Roles;
import sv.edu.udb.util.Validations;
import sv.edu.udb.vistas.Contenedor;

/**
 *
 * @author kiss_
 */
public class EditUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditUser
     */
   DeparmentController dep = new DeparmentController();
    RolController rol = new RolController();
    Deparment liDep = new Deparment();
    Rol liRol = new Rol();
    Employee employee = new Employee();
    EmployeeController ec = new EmployeeController();
    Deparment d = new Deparment();
    Rol r = new Rol();
    Validations valid=new Validations();
    public EditUser() {
        initComponents();
        cmbbxDepoto.removeAllItems();
        cmbbxTipoEmpleado.removeAllItems();
        
    }
    
        public EditUser(int id) {
        initComponents();
        this.employee = ec.getEmployeeById(id);
        fillCombos();
        fillInputs();
        
    }
        
        public void fillInputs(){
            d= dep.showDeparment(employee.getDepartmentId());
        r = rol.getRol(employee.getRolId());
            txtName.setText(employee.getEmployeeName());
            txtLastname.setText(employee.getEmployeeLastname());
            txtUsuario.setText(employee.getUsername());
//            txtContra.setText(employee.getPassword());
             cmbbxDepoto.setSelectedIndex(0);
             cmbbxTipoEmpleado.setSelectedIndex(0);

            
        }
        public  void fillCombos(){
           
            liDep = dep.showDeparment(Session.deparmentId);
            liRol = rol.getRol(employee.getRolId());
           
        cmbbxDepoto.removeAllItems();
        cmbbxTipoEmpleado.removeAllItems();

       
            cmbbxDepoto.addItem(liDep.getDepartmentName());
            cmbbxTipoEmpleado.addItem(liRol.getRolName());       
        }
        
        public void hidePassword(){
            if (Session.employeeType == Roles.ADMINISTRADOR.getRolId()) {
            lblContra.setVisible(false);
            txtContra.setVisible(false);
            }
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContra = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblDepto = new javax.swing.JLabel();
        cmbbxDepoto = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        cmbbxTipoEmpleado = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblUsers = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNcontra = new javax.swing.JPasswordField();

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(35, 10, 89));
        lblTitulo.setText("Editar Empleado");

        btnEditar.setBackground(new java.awt.Color(35, 10, 89));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblDepto.setForeground(new java.awt.Color(0, 41, 250));
        lblDepto.setText("Departamento:");

        cmbbxDepoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipo.setForeground(new java.awt.Color(0, 41, 250));
        lblTipo.setText("Tipo de empleado:");

        cmbbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombre.setForeground(new java.awt.Color(0, 41, 250));
        lblNombre.setText("Nombre:");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        lblApellido.setForeground(new java.awt.Color(0, 41, 250));
        lblApellido.setText("Apellido:");

        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastnameKeyPressed(evt);
            }
        });

        lblUsers.setForeground(new java.awt.Color(0, 41, 250));
        lblUsers.setText("Usuario:");

        lblContra.setForeground(new java.awt.Color(0, 41, 250));
        lblContra.setText("Contraseña:");

        jLabel1.setForeground(new java.awt.Color(0, 40, 250));
        jLabel1.setText("Nueva contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsers)
                        .addComponent(lblApellido)
                        .addComponent(lblNombre))
                    .addComponent(lblDepto)
                    .addComponent(lblTipo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblContra))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbbxTipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbbxDepoto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastname)
                    .addComponent(txtName)
                    .addComponent(txtUsuario)
                    .addComponent(txtContra, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtNcontra, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbbxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbxDepoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepto))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
       Employee user = new Employee();
        DeparmentController depto = new DeparmentController();
        RolController rolUser = new RolController();
        Deparment d;
        user.setEmployeeId(employee.getEmployeeId());
        
        if (validationTxt()){
                    String[] p ={"Name","Lastname"};        
                    String pass = new String(txtContra.getPassword());
                    String npass = new String(txtNcontra.getPassword());
                    user.setEmployeeName(txtName.getText());
                    user.setEmployeeLastname(txtLastname.getText());
                    user.setUsername(txtUsuario.getText());
                    user.setPassword(npass);
                    d=depto.showDepartment(cmbbxDepoto.getSelectedItem().toString());

                    user.setDepartmentId(d.getDepartmentId());
                    user.setRolId(rolUser.showID(cmbbxTipoEmpleado.getSelectedItem().toString()));



                    if(ec.updateEmployee(user, p, pass)){
                        JOptionPane.showMessageDialog(null, "El usuario se ha editado correctamente","Operacion exitosa",JOptionPane.INFORMATION_MESSAGE );
                         ShowUsers su = new ShowUsers();
                        Contenedor.desktopPane.removeAll();
                        Contenedor.desktopPane.updateUI();
                        Contenedor.desktopPane.add(su);
                        this.dispose();
                        su.show();
                        cleanTxt();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "El usuario no se ha editado correctamente","Operacion fallida",JOptionPane.ERROR_MESSAGE );
                        cleanTxt();
                    }
        }
         else{
                        JOptionPane.showMessageDialog(null, "El usuario no se ha editado correctamente","Operacion fallida",JOptionPane.ERROR_MESSAGE );
                        cleanTxt();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        valid.numberTyped(evt);
       
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtLastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyPressed
        // TODO add your handling code here:
        valid.numberTyped(evt);
       
    }//GEN-LAST:event_txtLastnameKeyPressed
    public boolean validationTxt(){
        if (valid.checkPassword(txtContra.getPassword()) && valid.checkPassword(txtNcontra.getPassword()) &&  !valid.emptyField(txtName.getText()) && !valid.emptyField(txtLastname.getText()) && !valid.emptyField(txtUsuario.getText()) && !valid.emptyField(txtContra.getText())) {
            return true;
        }
        else{
            return false;
        }
    }
     public void cleanTxt(){
         txtName.setText("");
         txtLastname.setText("");
         txtContra.setText("");
         txtNcontra.setText("");
         txtUsuario.setText("");
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cmbbxDepoto;
    private javax.swing.JComboBox<String> cmbbxTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblDepto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNcontra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
