/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.employessviews;

import java.util.List;
import sv.edu.udb.models.Employee;
import sv.edu.udb.models.Session;
import sv.edu.udb.controllers.EmployeeController;

/**
 *
 * @author kiss_
 */
public class ShowUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowUsers
     */
     List<Employee> supervisores;
     List<Employee> empleados;
     EmployeeController ec = new EmployeeController();
    
    public ShowUsers() {
        initComponents();
//        Aqui se deben inicializar los 
        
        
        if(Session.employeeType != 5){
            panedUsers.setEnabledAt(1, false);
        }
        switch(Session.employeeType){
            case 1:
                empleados=ec.findEmployee(2, Session.deparmentId);
                break;
                
            case 3:
                empleados=ec.findEmployee(4, Session.deparmentId);
                break;
                
            case 5:
                empleados=ec.findEmployees();
                break;
        }
        supervisores=ec.findSupervisors();
        
        showEmployees();
        showSupervisors();
    }

    public void showEmployees(){
        String matriz[][] = new String[empleados.size()][4];
        
        for (int i = 0; i < empleados.size(); i++) {
            matriz[i][0]= empleados.get(i).getEmployeeName();
            matriz[i][1]= empleados.get(i).getEmployeeLastname();
            matriz[i][2]= Integer.toString(empleados.get(i).getDepartmentId());
            matriz[i][3]= empleados.get(i).getUsername();
        }
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
        matriz,
        new String[]{
            "Nombre", "Apellido","Departamento", "Usuario"
        }
        ));

    }
    
       public void showSupervisors(){
        String matriz[][] = new String[supervisores.size()][4];
        
        for (int i = 0; i < supervisores.size(); i++) {
            matriz[i][0]= supervisores.get(i).getEmployeeName();
            matriz[i][1]= supervisores.get(i).getEmployeeLastname();
            matriz[i][2]= Integer.toString(supervisores.get(i).getDepartmentId());
            matriz[i][3]= supervisores.get(i).getUsername();
        }
        tblSupervisor.setModel(new javax.swing.table.DefaultTableModel(
        matriz,
        new String[]{
            "Nombre", "Apellido","Departamento", "Usuario"
        }
        ));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        panedUsers = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupervisor = new javax.swing.JTable();

        btnEdit.setText("Editar");

        btnDelete.setText("Eliminar");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("Listado de Usuarios");

        panedUsers.setVerifyInputWhenFocusTarget(false);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEmployee);

        panedUsers.addTab("Empleados por depto.", jScrollPane2);

        tblSupervisor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Departamento", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupervisor);

        panedUsers.addTab("Supervisores", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panedUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(57, 57, 57))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblTitulo)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(panedUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTabbedPane panedUsers;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblSupervisor;
    // End of variables declaration//GEN-END:variables
}
