/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.employessviews;

import java.util.List;
import javax.swing.JOptionPane;
import sun.awt.EmbeddedFrame;
import sv.edu.udb.models.Employee;
import sv.edu.udb.models.Session;
import sv.edu.udb.controllers.EmployeeController;
import sv.edu.udb.vistas.Contenedor;

/**
 *
 * @author kiss_
 */
public class ShowUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowUsers
     */
    private List<Employee> supervisores;
    private List<Employee> empleados;
    private EmployeeController ec = new EmployeeController();
    private Employee employeeSelected = new Employee();
    private int employeeId = -1;

    public ShowUsers() {
        initComponents();
//        Aqui se deben inicializar los 

        loadData();
        if (Session.employeeType != 5) {
            panedUsers.setEnabledAt(1, false);
        } else {
            showSupervisors();
        }
        showEmployees();
    }

    public void showEmployees() {
        String matriz[][] = new String[empleados.size()][5];

        for (int i = 0; i < empleados.size(); i++) {
            matriz[i][0] = Integer.toString(empleados.get(i).getEmployeeId());
            matriz[i][1] = empleados.get(i).getEmployeeName();
            matriz[i][2] = empleados.get(i).getEmployeeLastname();
            matriz[i][3] = Integer.toString(empleados.get(i).getDepartmentId());
            matriz[i][4] = empleados.get(i).getUsername();
        }
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Nombre", "Apellido", "Departamento", "Usuario"
                }
        ));

    }

    public void showSupervisors() {
        String matriz[][] = new String[supervisores.size()][5];

        for (int i = 0; i < supervisores.size(); i++) {
            matriz[i][0] = Integer.toString(supervisores.get(i).getEmployeeId());
            matriz[i][1] = supervisores.get(i).getEmployeeName();
            matriz[i][2] = supervisores.get(i).getEmployeeLastname();
            matriz[i][3] = Integer.toString(supervisores.get(i).getDepartmentId());
            matriz[i][4] = supervisores.get(i).getUsername();
        }
        tblSupervisor.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Nombre", "Apellido", "Departamento", "Usuario"
                }
        ));

    }

    public void loadData() {
        switch (Session.employeeType) {
            case 1:
                empleados = ec.findEmployee(2, Session.deparmentId);
                break;

            case 3:
                empleados = ec.findEmployee(4, Session.deparmentId);
                break;

            case 5:
                empleados = ec.findEmployees();
                supervisores = ec.findSupervisors();
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        panedUsers = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupervisor = new javax.swing.JTable();

        btnEdit.setBackground(new java.awt.Color(35, 10, 89));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(35, 10, 89));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(35, 10, 89));
        lblTitulo.setText("Listado de Usuarios");

        panedUsers.setVerifyInputWhenFocusTarget(false);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployee);

        panedUsers.addTab("Empleados por depto.", jScrollPane2);

        tblSupervisor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Departamento", "Title 4", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupervisor);

        panedUsers.addTab("Supervisores", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panedUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(57, 57, 57))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblTitulo)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(panedUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int rowSelected = tblEmployee.rowAtPoint(evt.getPoint());
        employeeSelected.setEmployeeId(Integer.parseInt((String) tblEmployee.getValueAt(rowSelected, 0)));
        employeeSelected.setEmployeeName((String) tblEmployee.getValueAt(rowSelected, 1));
        employeeSelected.setEmployeeLastname((String) tblEmployee.getValueAt(rowSelected, 2));
        employeeId = Integer.parseInt((String) tblEmployee.getValueAt(rowSelected, 0));
        JOptionPane.showMessageDialog(rootPane, employeeId);
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (employeeId != -1) {
            EditUser su = new EditUser(employeeSelected.getEmployeeId());
            Contenedor.desktopPane.removeAll();
            Contenedor.desktopPane.updateUI();
            Contenedor.desktopPane.add(su);
            this.dispose();
            su.show();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un empleado a editar", "Empleado No seleccionado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (employeeId != -1) {
            employeeSelected.setEmployeeId(employeeId);
            int res = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar al empleado " + employeeSelected.getEmployeeName() + " " + employeeSelected.getEmployeeLastname() + "?", "Eliminar empleado", JOptionPane.WARNING_MESSAGE);
            if (JOptionPane.YES_OPTION == res) {
                if (ec.deleteEmployee(employeeSelected)) {
                    JOptionPane.showMessageDialog(rootPane, "El empleado ha sido eliminado", "Empleado eliminado", JOptionPane.INFORMATION_MESSAGE);
                    showEmployees();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El empleado no ha sido eliminado", "Empleado no eliminado", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "El empleado no ha sido eliminado", "Empleado no eliminado", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un empleado a eliminar", "Empleado No seleccionado", JOptionPane.WARNING_MESSAGE);
        }
        loadData();
        showEmployees();
        if (Session.employeeType != 5) {
            showSupervisors();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTabbedPane panedUsers;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblSupervisor;
    // End of variables declaration//GEN-END:variables
}
