/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas;

/**
 *
 * @author kiss_
 */
public class ViewTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewTicket
     */
    public ViewTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListaTicket = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTickets = new javax.swing.JList<>();
        lblTicketName = new javax.swing.JLabel();
        lblTituloDesc = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblTitleAct = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitleStatus = new javax.swing.JLabel();
        lblSupervisorTI = new javax.swing.JLabel();
        lblTitleSupervisor = new javax.swing.JLabel();
        lblTitleSupervisor1 = new javax.swing.JLabel();
        lblSupervisorFunc = new javax.swing.JLabel();
        lblTitleProgramador1 = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        lblFecgaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JFormattedTextField();
        cmbProgramador = new javax.swing.JComboBox<>();
        cmbTester = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JTextField();
        chckbQA = new javax.swing.JCheckBox();
        lblTitleStatus1 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionProgram = new javax.swing.JTextArea();
        lblCodigo = new javax.swing.JLabel();

        pnlListaTicket.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitulo1.setText("Lista de Tickets");

        listTickets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listTickets);

        javax.swing.GroupLayout pnlListaTicketLayout = new javax.swing.GroupLayout(pnlListaTicket);
        pnlListaTicket.setLayout(pnlListaTicketLayout);
        pnlListaTicketLayout.setHorizontalGroup(
            pnlListaTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTicketLayout.createSequentialGroup()
                .addGroup(pnlListaTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListaTicketLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListaTicketLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitulo1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlListaTicketLayout.setVerticalGroup(
            pnlListaTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTicketLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTicketName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTicketName.setText("Nombre del Ticket");

        lblTituloDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTituloDesc.setText("Descripción");

        lblDescription.setText("jLabel1");

        lblTitleAct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitleAct.setText("Actividad");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblTitleStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleStatus.setText("Estado");

        lblSupervisorTI.setText("Jorge Lopez");

        lblTitleSupervisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleSupervisor.setText("Supervisor de TI");

        lblTitleSupervisor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleSupervisor1.setText("Supervisor funcional");

        lblSupervisorFunc.setText("Alexis Rosales");

        lblTitleProgramador1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleProgramador1.setText("Programador asignado");

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaInicio.setText("Fecha de inicio");

        txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtFechaInicio.setText("Ej. 03-05-2020");

        lblFecgaFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecgaFin.setText("Fecha de finalización");

        txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtFechaFin.setText("Ej. 03-07-2020");

        cmbProgramador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtStatus.setText("Esperando aprobación");

        chckbQA.setBackground(new java.awt.Color(204, 204, 255));
        chckbQA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chckbQA.setText("Q/A asignado");
        chckbQA.setToolTipText("Al hacer click, solicitará un Terter");

        lblTitleStatus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleStatus1.setText("Avance");

        txtPorcentaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        txtPorcentaje.setText("12%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitleStatus1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPorcentaje, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbProgramador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaFin)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblFecgaFin)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblSupervisorTI)
                                                            .addComponent(lblTitleSupervisor1)
                                                            .addComponent(lblSupervisorFunc))
                                                        .addComponent(lblTitleProgramador1))
                                                    .addComponent(lblFechaInicio)
                                                    .addComponent(txtFechaInicio)
                                                    .addComponent(cmbTester, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(chckbQA))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitleSupervisor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitleStatus, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblTitleStatus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblTitleStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblTitleSupervisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupervisorTI)
                .addGap(18, 18, 18)
                .addComponent(lblTitleSupervisor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupervisorFunc)
                .addGap(23, 23, 23)
                .addComponent(lblTitleProgramador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProgramador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chckbQA)
                .addGap(18, 18, 18)
                .addComponent(cmbTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFecgaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        txtDescripcionProgram.setColumns(20);
        txtDescripcionProgram.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionProgram);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigo.setText("CD2020");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlListaTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloDesc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblTitleAct))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDescription)
                                        .addGap(56, 56, 56))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addComponent(lblTicketName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCodigo)
                        .addGap(34, 34, 34)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListaTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addGap(26, 26, 26)
                .addComponent(lblTicketName)
                .addGap(49, 49, 49)
                .addComponent(lblTituloDesc)
                .addGap(42, 42, 42)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTitleAct)
                .addGap(97, 97, 97))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chckbQA;
    private javax.swing.JComboBox<String> cmbProgramador;
    private javax.swing.JComboBox<String> cmbTester;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFecgaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblSupervisorFunc;
    private javax.swing.JLabel lblSupervisorTI;
    private javax.swing.JLabel lblTicketName;
    private javax.swing.JLabel lblTitleAct;
    private javax.swing.JLabel lblTitleProgramador1;
    private javax.swing.JLabel lblTitleStatus;
    private javax.swing.JLabel lblTitleStatus1;
    private javax.swing.JLabel lblTitleSupervisor;
    private javax.swing.JLabel lblTitleSupervisor1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTituloDesc;
    private javax.swing.JList<String> listTickets;
    private javax.swing.JPanel pnlListaTicket;
    private javax.swing.JTextArea txtDescripcionProgram;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JFormattedTextField txtPorcentaje;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
