CREATE SCHEMA IF NOT EXISTS `gestion_tickets`;
USE `gestion_tickets` ;

CREATE TABLE IF NOT EXISTS `gestion_tickets`.`departments` (
  `DEPARTMENTID` SMALLINT NOT NULL AUTO_INCREMENT,
  `DEPARTMENTNAME` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`DEPARTMENTID`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

CREATE TABLE IF NOT EXISTS `gestion_tickets`.`roles` (
  `ROLID` SMALLINT NOT NULL AUTO_INCREMENT,
  `ROLNAME` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ROLID`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

CREATE TABLE IF NOT EXISTS `gestion_tickets`.`employees` (
  `EmployeeID` SMALLINT NOT NULL AUTO_INCREMENT,
  `ROLID` SMALLINT NOT NULL,
  `DEPARTMENTID` SMALLINT NOT NULL,
  `EMPLOYEENAME` VARCHAR(64) NOT NULL,
  `EMPLOYEELASTNAME` VARCHAR(64) NOT NULL,
  `USERNAME` VARCHAR(16) NOT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`EmployeeID`, `DEPARTMENTID`),
  CONSTRAINT `FK_REL_DEPARTMENT_EMPLOYEE`
        FOREIGN KEY (`DEPARTMENTID`)
        REFERENCES `gestion_tickets`.`departments` (`DEPARTMENTID`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
  CONSTRAINT `FK_REL_ROL_EMPLOYEE`
        FOREIGN KEY (`ROLID`)
        REFERENCES `gestion_tickets`.`roles` (`ROLID`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

CREATE TABLE IF NOT EXISTS `gestion_tickets`.`comments` (
  `COMMENTID` SMALLINT NOT NULL AUTO_INCREMENT,
  `EMPLOYEEID` SMALLINT NOT NULL,
  `DEPARTMENTID` SMALLINT NOT NULL,
  `REQUESTID` SMALLINT NOT NULL,
  `COMMENTTEXT` VARCHAR(2048) NOT NULL,
  `COMMENTDATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`COMMENTID`, `DEPARTMENTID`, `EMPLOYEEID`, `REQUESTID`),
  CONSTRAINT `FK_REL_EMPLOYEE_REQUEST`
        FOREIGN KEY (`REQUESTID`)
        REFERENCES `gestion_tickets`.`requests` (`REQUESTID`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
  CONSTRAINT `fk_comments_employees1`
        FOREIGN KEY (`EMPLOYEEID` , `DEPARTMENTID`)
        REFERENCES `gestion_tickets`.`employees` (`EmployeeID` , `DEPARTMENTID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


CREATE TABLE IF NOT EXISTS `gestion_tickets`.`projects` (
  `PROJECTID` SMALLINT NOT NULL AUTO_INCREMENT,
  `DEPARTMENTID` SMALLINT NOT NULL,
  `PROJECTNAME` VARCHAR(256) NOT NULL,
  `PROJECTDESCRIPTION` VARCHAR(1024) NOT NULL,
  `CREATIONDATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`PROJECTID`),
  CONSTRAINT `fk_projects_departments1`
        FOREIGN KEY (`DEPARTMENTID`)
        REFERENCES `gestion_tickets`.`departments` (`DEPARTMENTID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

CREATE TABLE IF NOT EXISTS `gestion_tickets`.`tickets` ( 
    `TICKETID` SMALLINT NOT NULL AUTO_INCREMENT, 
    `REQUESTID` SMALLINT NOT NULL, 
    `PROJECTID` SMALLINT NOT NULL,
    `ID_PROGRAMADOR` SMALLINT NOT NULL,
    `ID_TESTER` SMALLINT NOT NULL,
    `TICKET_STATUS` VARCHAR(48) NOT NULL, 
    `INTERNALCODE` VARCHAR(24) NOT NULL, 
    `STARTDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `ENDDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (`TICKETID`, `REQUESTID`), 
    CONSTRAINT `fk_tickets_requests1` 
        FOREIGN KEY (`REQUESTID`) 
        REFERENCES `gestion_tickets`.`requests` (`REQUESTID`) 
        ON DELETE CASCADE 
        ON UPDATE NO ACTION) 
ENGINE = InnoDB 
AUTO_INCREMENT = 0;