/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.vistas.report;

import java.util.Date;
import sv.edu.udb.models.Report;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.util.Connect;

/**
 *
 * @author marta
 */
public class ReportView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReportView
     *
     */
    DefaultTableModel modelo1=null;
    static int bandera=0;
    ResultSet resultado=null;
    Report repo = new Report();
    public ReportView() {
        bandera=1;
        initComponents();
        Object [][] data=null;
        String [] columns = {"Nombre","Apellido","Status","Cantidad","Fecha Inicio","Fecha concluido"};
        modelo1= new DefaultTableModel(data,columns);
        this.jTableResult.setModel(modelo1);
        
        
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        DateStart = new com.toedter.calendar.JDateChooser();
        DateFinish = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el codigo del programador");

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Empleado", "Apellido Empleado", "Casos", "Cantidad", "Fecha de inicio", "fecha de finalizacion"
            }
        ));
        jScrollPane1.setViewportView(jTableResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateFinish, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(DateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(DateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(DateFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connect cc =new Connect();
            
            PreparedStatement ps = null;
            ResultSet rs=null;
            int id;          
            
        
        
        id=Integer.valueOf(txtId.getText());
            Date dates1 =DateStart.getDate();
            Date dates2 =DateFinish.getDate();
            long ds = dates1.getTime();
            long d = dates2.getTime();
            
            Date datecn= new Date(ds);
            Date datecn2= new Date(ds);
        
         cc.setRs("SELECT employees.EMPLOYEENAME, employees.EMPLOYEELASTNAME, "
                 + "tickets.TICKET_STATUS,COUNT(tickets.TICKET_STATUS),"
                 + "tickets.STARTDATE,"
                 + "tickets.ENDDATE from employees INNER JOIN tickets on "
                 + "employees.EmployeeID=tickets.ID_PROGRAMADOR "
                 + "WHERE employees.EmployeeID= "+id+" AND "
                 + "tickets.STARTDATE BETWEEN "+datecn+" "
                 + "and "+datecn2);
         
         ResultSet report = (ResultSet) cc.getRs();
         while (report.next()) {
                Object [] newRow = {report.getString(1),report.getString(2),report.getString(3),report.getInt(4),report.getDate(5),report.getDate(6)};
                modelo1.addRow(newRow);
            } 
         
        
      
         
         
        
        
        
        String file_name="\\src\\sv\\edu\\udb\\Report\\Report.pdf";    
        Document document =new Document();
    
    PdfWriter.getInstance(document, new FileOutputStream(file_name));
    document.open();
    Paragraph titulo=new Paragraph ("Reporte de casos");
    document.add(titulo);
    PdfPTable table = new PdfPTable(6); 
    PdfPCell c1 = new PdfPCell(new Phrase("Nombre empleado"));
    table.addCell(c1);
    c1 = new PdfPCell(new Phrase("Apellido empleado"));
    table.addCell(c1);
    c1 = new PdfPCell(new Phrase("Estado de Ticket"));
    table.addCell(c1);
    c1 = new PdfPCell(new Phrase("Cantidad"));
    table.addCell(c1);
    c1 = new PdfPCell(new Phrase("Fecha de inicio"));
    table.addCell(c1);
    c1 = new PdfPCell(new Phrase("Fecha de finalizacion"));
    table.addCell(c1);
    table.setHeaderRows(1);
    
    
    table.addCell(report.getString("employees.EMPLOYEENAME"));
    table.addCell(report.getString("employees.EMPLOYEELASTNAME"));
    table.addCell(report.getString("tickets.TICKET_STATUS"));
    table.addCell(report.getString("COUNT(tickets.TICKET_STATUS)"));
    table.addCell(report.getString("tickets.STARTDATE"));
    table.addCell(report.getString("tickets.ENDDATE"));
    
    
    
    
    document.close();
        
        
        
        
        
        
        
            
        } catch (SQLException ex) {
             Logger.getLogger(ReportView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(ReportView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateFinish;
    private com.toedter.calendar.JDateChooser DateStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
